### ISSUE TITLE
License and commercial use

### ISSUE THREAD

**Issue by axekan** [stevage/map-gl-utils#39]
Hello, I'm finding this library very convenient in my commercial mapbox application (not yet published) but noticed this repository doesn't have any license specified.

What is your current standpoint on this? Would you be able to add a license? Since there is none available, [default copyright laws apply to use of this code](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license).

Thank you.

**Comment by stevage** [comment]
Hi @axekan, please contact me at me@stevebennett.me to discuss commercial licensing.
